# Generated by Django 3.0.2 on 2020-03-11 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkersTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('pssword', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MessagesTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('isUnread', models.BooleanField()),
                ('isAccepted', models.BooleanField()),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workersTable', to='app1.WorkersTable')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MessagesTable', to='app1.WorkersTable')),
            ],
        ),
    ]
