# Generated by Django 3.0.2 on 2020-03-11 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMembersTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamnumber', models.IntegerField()),
                ('isRated', models.BooleanField()),
                ('isSupervisor', models.BooleanField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workersTable2', to='app1.WorkersTable')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TeamMembersTable', to='app1.WorkersTable')),
            ],
        ),
    ]
