# Generated by Django 3.0.2 on 2020-03-12 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20200312_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammemberstable',
            name='member',
        ),
        migrations.AddField(
            model_name='teammemberstable',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workersTable3', to='app1.WorkersTable'),
        ),
    ]
