# Generated by Django 3.0.2 on 2020-03-15 03:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20200312_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagestable',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='messagestable',
            name='dealers',
            field=models.ManyToManyField(to='app1.WorkersTable'),
        ),
    ]
