# Generated by Django 3.0.2 on 2020-03-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20200315_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagestable',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
