# Generated by Django 3.0.2 on 2020-03-27 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20200324_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftstable',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='shiftstable',
            name='name',
        ),
        migrations.RemoveField(
            model_name='shiftstable',
            name='startTime',
        ),
        migrations.RemoveField(
            model_name='shiftstable',
            name='type',
        ),
        migrations.AddField(
            model_name='shiftstable',
            name='date',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='shiftstable',
            name='isDay',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shiftstable',
            name='massagekey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.MessagesTable'),
        ),
        migrations.DeleteModel(
            name='ShiftLogTable',
        ),
    ]
